-- ============================================================
-- SEED: Full sighting data for the 10 Mt. Busa orchids.
-- Fills every submission-form field for each species_sightings record.
-- Run in the Supabase SQL Editor AFTER the main schema migrations.
-- Uses ON CONFLICT (entry_id) DO UPDATE so it is safe to re-run.
-- ============================================================

BEGIN;

-- ── 1. Aerides quinquevulnera ─────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-AQ-001', 'Aerides quinquevulnera', 'Aerides',
  '["Five-spotted Aerides", "Five-wounded Aerides", "Pink Aerides"]'::jsonb,
  '["Talisay", "Sampaguita sa Bundok"]'::jsonb,
  'Confirmed', 'yes',
  '2024-03-15', '09:30:00', 'transect', 'flowering', false,
  'Mt. Busa', 'trail', 6.1821, 124.3482, 1050.00,
  'montane forest', 'canopy', 'tree bark',
  'Ficus subcordata', 45.50, 80.00, 'partial',
  NULL, 'stream',
  35.00, false, 25.00, 18.00,
  8, 'Linear & Narrow', 22.00, 3.50,
  '["Smooth", "Leathery"]'::jsonb, 'Alternate',
  'White with purple-pink spots', 18, 2.50,
  'Raceme', 'Spatulate', 'Ovate, white with rose-pink spots and purple blotch at tip',
  'Trilobed (Three-lobed)', 'Sweet', 'Full Bloom', 'March–June',
  false, NULL, NULL,
  'Mature', 'flowering', 6, 'rare',
  'Vulnerable', '["Habitat loss", "Overcollection"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Ana Magtibay, Roel Cañete',
  'Found growing on large Ficus along the main Mt. Busa trail. Healthy colony of 6 plants in active flowering. Leaves dark green with silvery midrib. Strong sweet fragrance detectable at 1m distance.',
  'Dr. Maria Santos Reyes', 'Jomar Dela Cruz', 'Ana Magtibay',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 2. Bulbophyllum lobbii ────────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-BL-001', 'Bulbophyllum lobbii', 'Bulbophyllum',
  '["Lobb''s Bulbophyllum", "Yellow Bulbophyllum"]'::jsonb,
  '["Bulbul na Orchid", "Kalimba"]'::jsonb,
  'Confirmed', 'no',
  '2024-04-08', '08:15:00', 'opportunistic', 'live specimen', false,
  'Mt. Busa', 'ridge', 6.1754, 124.3521, 1250.00,
  'mossy forest', 'understory', 'tree bark',
  'Podocarpus philippinensis', 38.00, 90.00, 'partial',
  NULL, 'seep',
  12.00, true, 8.00, 10.00,
  1, 'Rounded & Oval', 18.00, 6.00,
  '["Smooth", "Leathery", "Glossy"]'::jsonb, 'Alternate',
  'Yellow with red-brown veins and stripes', 1, 7.00,
  'Solitary', 'Obovate', 'Broadly ovate, pale yellow with reddish nerves',
  'Saccate (Bag-like)', 'Faint', 'Full Bloom', 'April–August',
  false, NULL, NULL,
  'Mature', 'flowering', 4, 'rare',
  'Vulnerable', '["Habitat loss", "Logging"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Lorna Gabas',
  'Single-flowered epiphyte on mossy Podocarpus at ridge. Pseudobulbs ovoid, 3–4 cm, closely spaced on creeping rhizome. Flower solitary, nodding, with distinctive foul-sweet scent attracting flies.',
  'Dr. Maria Santos Reyes', 'Lorna Gabas', 'Jomar Dela Cruz',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 3. Calanthe triplicata ────────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-CT-001', 'Calanthe triplicata', 'Calanthe',
  '["White Calanthe", "Triplefolded Calanthe", "Christmas Orchid"]'::jsonb,
  '["Puting Orkidyas", "Kahoy na Puting Bulaklak"]'::jsonb,
  'Confirmed', 'no',
  '2024-02-20', '10:00:00', 'transect', 'flowering', false,
  'Mt. Busa', 'streamside', 6.1892, 124.3445, 800.00,
  'montane forest', 'forest floor', 'soil',
  NULL, NULL, 75.00, 'full shade',
  'loamy', 'stream',
  60.00, true, 40.00, 20.00,
  4, 'Rounded & Oval', 45.00, 12.00,
  '["Smooth", "Waxy"]'::jsonb, 'Alternate',
  'Pure white with orange-yellow callus on lip', 20, 3.50,
  'Raceme', 'Obovate', 'Spreading, pure white, broadly ovate',
  'Trilobed (Three-lobed)', 'Faint', 'Full Bloom', 'February–April',
  false, NULL, NULL,
  'Mature', 'flowering', 15, 'common',
  'Least Concern', '["Habitat disturbance"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Ana Magtibay, Roel Cañete, Ben Lumapas',
  'Terrestrial colony along streamside, soil rich in decomposed leaf litter. Pseudobulbs conical, closely set. Leaves large, pleated, heavily veined. Very common at this site — largest colony observed with 15 plants. White flowers with yellow-orange callus are diagnostic.',
  'Ana Magtibay', 'Dr. Maria Santos Reyes', 'Roel Cañete',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, soil_type = EXCLUDED.soil_type,
  nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 4. Coelogyne asperata ─────────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-CA-001', 'Coelogyne asperata', 'Coelogyne',
  '["Rough Coelogyne", "Rough-surfaced Coelogyne"]'::jsonb,
  '["Batingaw na Orchid", "Garing-garing"]'::jsonb,
  'Confirmed', 'no',
  '2024-05-12', '07:45:00', 'transect', 'flowering', false,
  'Mt. Busa', 'trail', 6.1668, 124.3389, 650.00,
  'lowland forest', 'understory', 'tree bark',
  'Pterocarpus indicus', 62.00, 70.00, 'partial',
  NULL, 'river',
  50.00, true, 35.00, 22.00,
  2, 'Rounded & Oval', 40.00, 10.00,
  '["Smooth", "Leathery"]'::jsonb, 'Alternate',
  'Cream-white with brown-orange keels on lip', 8, 6.00,
  'Raceme', 'Obovate', 'Pale cream to ivory-white, spreading, slightly reflexed',
  'Trilobed (Three-lobed)', 'Sweet', 'Anthesis (Early)', 'May–August',
  false, NULL, NULL,
  'Mature', 'flowering', 3, 'rare',
  'Vulnerable', '["Habitat loss", "Deforestation"]'::jsonb,
  'Lorna Gabas', 'MSU-General Santos Institute of Environmental Studies',
  'Roel Cañete, Jun Mascarinas',
  'Epiphyte on mature Pterocarpus at lower trail elevation. Pseudobulbs elongate-ovoid, 10–12 cm, yellowish-green. Two large apical leaves per pseudobulb. Inflorescence pendant with 8 fragrant cream flowers. Brown-orange ridges on lip are diagnostic for species.',
  'Lorna Gabas', 'Lorna Gabas', 'Roel Cañete',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 5. Dendrobium secundum ────────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-DS-001', 'Dendrobium secundum', 'Dendrobium',
  '["Toothbrush Orchid", "Pink Dendrobium", "One-sided Dendrobium"]'::jsonb,
  '["Suklay-suklay", "Sipit-sipit", "Brosang-Orkidyas"]'::jsonb,
  'Confirmed', 'yes',
  '2024-03-28', '08:00:00', 'transect', 'flowering', false,
  'Mt. Busa', 'ridge', 6.1935, 124.3562, 1150.00,
  'montane forest', 'canopy', 'tree bark',
  'Quercus merrittii', 55.00, 85.00, 'partial',
  NULL, 'spring',
  45.00, false, 38.00, 20.00,
  10, 'Linear & Narrow', 8.00, 1.80,
  '["Leathery", "Smooth"]'::jsonb, 'Alternate',
  'Bright pink-purple with white lip tube', 35, 1.20,
  'Raceme', 'Obovate', 'Pink, lanceolate, spreading horizontally',
  'Saccate (Bag-like)', 'None', 'Full Bloom', 'March–May',
  false, NULL, NULL,
  'Mature', 'flowering', 9, 'common',
  'Vulnerable', '["Overcollection", "Habitat loss"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Ana Magtibay, Jun Mascarinas',
  'Dense cluster on large Quercus branch at 8m height. Pseudocaulescent stems pendant, 30–50 cm. Flowers arranged on one side of stem only ("toothbrush" arrangement). Nine individual stems observed, several in peak bloom. Very showy from distance.',
  'Jun Mascarinas', 'Dr. Maria Santos Reyes', 'Jomar Dela Cruz',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 6. Paphiopedilum fowliei ──────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-PF-001', 'Paphiopedilum fowliei', 'Paphiopedilum',
  '["Fowlie''s Slipper Orchid", "Mindanao Slipper Orchid"]'::jsonb,
  '["Zapatilla", "Tsinelas ng Diyos", "Sinelas-sinelas"]'::jsonb,
  'Confirmed', 'yes',
  '2024-01-18', '09:00:00', 'quadrat', 'live specimen', true,
  'Mt. Busa', 'ridge', 6.2012, 124.3478, 1350.00,
  'mossy forest', 'rock surface', 'rock',
  NULL, NULL, 60.00, 'partial',
  'peaty', 'spring',
  25.00, false, NULL, 12.00,
  5, 'Linear & Narrow', 20.00, 4.00,
  '["Smooth", "Glossy"]'::jsonb, 'Alternate',
  'Pale pink dorsal sepal with green veins; rose-pink petals with dark spots; pouch pale pink', 1, 8.00,
  'Solitary', 'Spatulate', 'Dorsal sepal broadly ovate, white with green veins and slight pink flush',
  'Saccate (Bag-like)', 'None', 'Full Bloom', 'January–March',
  false, NULL, NULL,
  'Mature', 'flowering', 4, 'rare',
  'Endangered', '["Overcollection", "Habitat loss", "Illegal trade"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Ana Magtibay, Roel Cañete, DENR-XII Field Unit',
  'Critical species found on shaded limestone rock faces at ridge. Only 4 plants documented in this quadrat; highly vulnerable to collection. Voucher herbarium specimen deposited at MSU-GenSan herbarium. Coordination with DENR-XII for protection measures initiated.',
  'Dr. Maria Santos Reyes', 'Ana Magtibay', 'Roel Cañete',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, soil_type = EXCLUDED.soil_type,
  nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 7. Phalaenopsis schilleriana ──────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-PS-001', 'Phalaenopsis schilleriana', 'Phalaenopsis',
  '["Schiller''s Moth Orchid", "Pink Butterfly Orchid", "Mariposa Orchid"]'::jsonb,
  '["Mariposa", "Paruparo-paruparo", "Alibangbang na Orchid"]'::jsonb,
  'Confirmed', 'yes',
  '2024-02-10', '08:30:00', 'transect', 'flowering', false,
  'Mt. Busa', 'trail', 6.1723, 124.3413, 720.00,
  'lowland forest', 'understory', 'tree bark',
  'Ficus benjamina', 50.00, 75.00, 'partial',
  NULL, 'stream',
  30.00, false, 10.00, 25.00,
  4, 'Rounded & Oval', 35.00, 14.00,
  '["Smooth", "Leathery", "Glossy"]'::jsonb, 'Alternate',
  'Pale pink to rose-purple with deeper pink veining', 25, 5.50,
  'Panicle', 'Obovate', 'Broadly oval, pale pink, spreading',
  'Trilobed (Three-lobed)', 'Faint', 'Full Bloom', 'February–April',
  false, NULL, NULL,
  'Mature', 'flowering', 5, 'rare',
  'Vulnerable', '["Overcollection", "Habitat loss", "Illegal trade"]'::jsonb,
  'Lorna Gabas', 'MSU-General Santos Institute of Environmental Studies',
  'Ana Magtibay, Ben Lumapas',
  'Epiphyte on Ficus at lower elevation. Leaves with distinctive silver-gray mottling on dark green surface — a key identifying character. Large pendant panicle with 25 pink flowers. Flat roots with green tips visible. Five plants in this section of trail.',
  'Lorna Gabas', 'Ana Magtibay', 'Ben Lumapas',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 8. Spathoglottis plicata ──────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-SP-001', 'Spathoglottis plicata', 'Spathoglottis',
  '["Philippine Ground Orchid", "Large Purple Spathoglottis", "Pleated Spathoglottis"]'::jsonb,
  '["Abukay", "Kampupot sa Bundok", "Lakatan na Orchid"]'::jsonb,
  'Confirmed', 'no',
  '2024-04-22', '10:30:00', 'random survey', 'live specimen', false,
  'Mt. Busa', 'streamside', 6.1845, 124.3502, 920.00,
  'montane forest', 'forest floor', 'soil',
  NULL, NULL, 65.00, 'direct',
  'clay', 'stream',
  70.00, true, 50.00, 30.00,
  3, 'Linear & Narrow', 60.00, 4.00,
  '["Smooth", "Waxy"]'::jsonb, 'Alternate',
  'Purple to magenta with yellow callus on lip', 12, 4.00,
  'Raceme', 'Obovate', 'Purple, ovate, spreading, slightly reflexed at tip',
  'Trilobed (Three-lobed)', 'Faint', 'Full Bloom', 'April–November',
  true, 'Capsule', 'Immature (Green)',
  'Mature', 'fruiting', 22, 'Abundant',
  'Least Concern', '["Habitat disturbance"]'::jsonb,
  'Ana Magtibay', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Ben Lumapas, Jun Mascarinas',
  'Most abundant orchid observed at this site. Large colony of 22 plants along streamside bank in open-to-partial light. Pseudobulbs onion-shaped, 4–5 cm. Leaves strongly pleated, 60 cm tall. Several plants with both flowers and immature capsules simultaneously. Fruit-set good, indicating active reproduction.',
  'Ana Magtibay', 'Ana Magtibay', 'Jun Mascarinas',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, soil_type = EXCLUDED.soil_type,
  nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present, fruit_type = EXCLUDED.fruit_type,
  seed_capsule_condition = EXCLUDED.seed_capsule_condition,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 9. Trichoglottis brachiata ────────────────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-TB-001', 'Trichoglottis brachiata', 'Trichoglottis',
  '["Philippine Trichoglottis", "Braided Trichoglottis", "Dark Orchid"]'::jsonb,
  '["Kayumanggi na Orchid", "Itim na Bulaklak", "Dikya"]'::jsonb,
  'Confirmed', 'yes',
  '2024-05-05', '07:30:00', 'transect', 'flowering', false,
  'Mt. Busa', 'trail', 6.1791, 124.3467, 1080.00,
  'montane forest', 'canopy', 'tree bark',
  'Shorea negrosensis', 70.00, 80.00, 'partial',
  NULL, 'seep',
  80.00, false, 65.00, 30.00,
  12, 'Linear & Narrow', 10.00, 2.50,
  '["Leathery", "Smooth"]'::jsonb, 'Alternate',
  'Dark maroon-purple with white lip and yellow callus', 5, 4.00,
  'Raceme', 'Elliptic', 'Dark maroon, elliptic-lanceolate with lighter margins',
  'Trilobed (Three-lobed)', 'Musky', 'Full Bloom', 'April–June',
  false, NULL, NULL,
  'Mature', 'flowering', 3, 'rare',
  'Endangered', '["Habitat loss", "Logging", "Overcollection"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Roel Cañete, Lorna Gabas',
  'Monopodial epiphyte climbing large Shorea trunk. Stems pendant, 60–80 cm, densely leaved. Flowers emerge in short axillary racemes. Distinctive dark maroon color with white trilobed lip. Musky fragrance noticeable up close. Three plants found — considered endangered at this site.',
  'Dr. Maria Santos Reyes', 'Roel Cañete', 'Lorna Gabas',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;


-- ── 10. Vanda sanderiana (Waling-Waling) ──────────────────────────────
INSERT INTO species_sightings (
  entry_id, scientific_name, genus,
  common_names, local_names,
  identification_confidence, endemic_to_philippines,
  observation_date, observation_time, collection_method, observation_type, voucher_collected,
  mountain_name, specific_site_zone, latitude, longitude, elevation_meters,
  habitat_type, microhabitat, growth_substrate,
  host_tree_species, host_tree_dbh_cm, canopy_cover_percent, light_exposure,
  soil_type, nearby_water_source,
  plant_height_cm, pseudobulb_present, stem_length_cm, root_length_cm,
  leaf_count, leaf_shape, leaf_length_cm, leaf_width_cm,
  leaf_textures, leaf_arrangement,
  flower_color, flower_count, flower_diameter_cm,
  inflorescence_type, petal_characteristics, sepal_characteristics,
  labellum_lip_description, fragrance, blooming_stage, flowering_season,
  fruit_present, fruit_type, seed_capsule_condition,
  life_stage, phenology, population_count, population_status,
  threat_level, threat_types,
  researcher_name, institution, team_members, researcher_notes,
  whole_plant_photographer, closeup_flower_photographer, habitat_photographer,
  review_status
) VALUES (
  'BLOOM-VS-001', 'Vanda sanderiana', 'Vanda',
  '["Waling-Waling", "Sander''s Vanda", "Queen of Philippine Flowers"]'::jsonb,
  '["Waling-waling", "Adlawon", "Bulak sa Kahoy"]'::jsonb,
  'Confirmed', 'yes',
  '2024-09-14', '08:00:00', 'quadrat', 'flowering', false,
  'Mt. Busa', 'trail', 6.1634, 124.3358, 580.00,
  'lowland forest', 'canopy', 'tree bark',
  'Dipterocarpus grandiflorus', 85.00, 60.00, 'direct',
  NULL, 'river',
  90.00, false, 75.00, 40.00,
  16, 'Linear & Narrow', 35.00, 5.50,
  '["Leathery", "Smooth", "Glossy"]'::jsonb, 'Alternate',
  'Upper petals pale pink; lower petals olive-brown with pink veining; lip rose-pink', 10, 10.00,
  'Raceme', 'Obovate', 'Upper dorsal sepal pink-white; lateral sepals yellowish-brown with reticulate dark veins',
  'Trilobed (Three-lobed)', 'Sweet', 'Full Bloom', 'August–October',
  false, NULL, NULL,
  'Mature', 'flowering', 2, 'rare',
  'Critically Endangered', '["Overcollection", "Illegal trade", "Habitat loss", "Climate change"]'::jsonb,
  'Dr. Maria Santos Reyes', 'MSU-General Santos College of Natural Sciences',
  'Jomar Dela Cruz, Ana Magtibay, Roel Cañete, Lorna Gabas, DENR-XII Wildlife Division',
  'Exceptional find — only 2 Waling-Waling plants documented at this site. Growing 6m up on large Dipterocarpus near river. Large flat raceme bears 10 flowers, each ~10 cm across. The national flower symbol of Mindanao. Coordinates withheld from public records per DENR conservation protocol. Exact location known only to research team and DENR.',
  'Dr. Maria Santos Reyes', 'Jomar Dela Cruz', 'Ana Magtibay',
  'approved'
)
ON CONFLICT (entry_id) DO UPDATE SET
  genus = EXCLUDED.genus,
  common_names = EXCLUDED.common_names, local_names = EXCLUDED.local_names,
  identification_confidence = EXCLUDED.identification_confidence,
  endemic_to_philippines = EXCLUDED.endemic_to_philippines,
  observation_date = EXCLUDED.observation_date, observation_time = EXCLUDED.observation_time,
  collection_method = EXCLUDED.collection_method, observation_type = EXCLUDED.observation_type,
  voucher_collected = EXCLUDED.voucher_collected,
  specific_site_zone = EXCLUDED.specific_site_zone,
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  elevation_meters = EXCLUDED.elevation_meters,
  habitat_type = EXCLUDED.habitat_type, microhabitat = EXCLUDED.microhabitat,
  growth_substrate = EXCLUDED.growth_substrate,
  host_tree_species = EXCLUDED.host_tree_species,
  host_tree_dbh_cm = EXCLUDED.host_tree_dbh_cm,
  canopy_cover_percent = EXCLUDED.canopy_cover_percent,
  light_exposure = EXCLUDED.light_exposure, nearby_water_source = EXCLUDED.nearby_water_source,
  plant_height_cm = EXCLUDED.plant_height_cm, pseudobulb_present = EXCLUDED.pseudobulb_present,
  stem_length_cm = EXCLUDED.stem_length_cm, root_length_cm = EXCLUDED.root_length_cm,
  leaf_count = EXCLUDED.leaf_count, leaf_shape = EXCLUDED.leaf_shape,
  leaf_length_cm = EXCLUDED.leaf_length_cm, leaf_width_cm = EXCLUDED.leaf_width_cm,
  leaf_textures = EXCLUDED.leaf_textures, leaf_arrangement = EXCLUDED.leaf_arrangement,
  flower_color = EXCLUDED.flower_color, flower_count = EXCLUDED.flower_count,
  flower_diameter_cm = EXCLUDED.flower_diameter_cm,
  inflorescence_type = EXCLUDED.inflorescence_type,
  petal_characteristics = EXCLUDED.petal_characteristics,
  sepal_characteristics = EXCLUDED.sepal_characteristics,
  labellum_lip_description = EXCLUDED.labellum_lip_description,
  fragrance = EXCLUDED.fragrance, blooming_stage = EXCLUDED.blooming_stage,
  flowering_season = EXCLUDED.flowering_season,
  fruit_present = EXCLUDED.fruit_present,
  life_stage = EXCLUDED.life_stage, phenology = EXCLUDED.phenology,
  population_count = EXCLUDED.population_count, population_status = EXCLUDED.population_status,
  threat_level = EXCLUDED.threat_level, threat_types = EXCLUDED.threat_types,
  researcher_name = EXCLUDED.researcher_name, institution = EXCLUDED.institution,
  team_members = EXCLUDED.team_members, researcher_notes = EXCLUDED.researcher_notes,
  whole_plant_photographer = EXCLUDED.whole_plant_photographer,
  closeup_flower_photographer = EXCLUDED.closeup_flower_photographer,
  habitat_photographer = EXCLUDED.habitat_photographer,
  review_status = EXCLUDED.review_status;

COMMIT;
