CREATE TABLE IF NOT EXISTS genus (
  genus_id SERIAL PRIMARY KEY,
  genus_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS orchids (
  orchid_id SERIAL PRIMARY KEY,
  sci_name TEXT UNIQUE NOT NULL,
  genus_id INTEGER NOT NULL REFERENCES genus(genus_id) ON DELETE RESTRICT,
  common_name TEXT,
  endemicity TEXT,
  date_discovered TIMESTAMPTZ
);

-- =========================
-- SAFE GENUS INSERT
-- =========================
INSERT INTO genus (genus_name)
VALUES
('Acanthophippium'),('Acriopsis'),('Agrostophyllum'),('Anoectochilus'),
('Appendicula'),('Blepharoglossum'),('Brachypeza'),('Bryobium'),
('Bulbophyllum'),('Calanthe'),('Cephalantheropsis'),('Cheirostylis'),
('Coelogyne'),('Corymborkis'),('Cryptostylis'),('Cylindrolobus'),
('Cymboglossum'),('Cystorchis'),('Dendrobium'),('Dendrochilum'),
('Dienia'),('Epiblastus'),('Epipogium'),('Erythrodes'),
('Grammatophyllum'),('Lepidogyne'),('Mycaranthes'),('Oberonia'),
('Octarrhena'),('Odontochilus'),('Oxystophyllum'),('Paraphaius'),
('Peristylus'),('Phaius'),('Phalaenopsis'),('Pholidota'),
('Phreatia'),('Pinalia'),('Podochilus'),('Pteroceras'),
('Renanthera'),('Rhomboda'),('Robiquetia'),('Spathoglottis'),
('Stichorkis'),('Taeniophyllum'),('Thelasis'),('Thrixspermum'),
('Trichotosia'),('Vanda'),('Vrydagzynea')
ON CONFLICT (genus_name) DO NOTHING;


-- =========================
-- SAFE ORCHIDS INSERT (108)
-- =========================
INSERT INTO orchids (genus_id, sci_name)
SELECT g.genus_id, s.name
FROM (
VALUES
('Acanthophippium','Acanthophippium mantinianum'),
('Acriopsis','Acriopsis liliifolia var. lilifolia'),
('Agrostophyllum','Agrostophyllum elongatum'),
('Agrostophyllum','Agrostophyllum loheri'),
('Anoectochilus','Anoectochilus sp.'),
('Appendicula','Appendicula crotalina'),
('Appendicula','Appendicula elmeri'),
('Appendicula','Appendicula leytensis'),
('Appendicula','Appendicula malindangensis'),
('Appendicula','Appendicula cf. pendula'),
('Appendicula','Appendicula undulata var. longicalcarata'),
('Appendicula','Appendicula weberi'),
('Appendicula','Appendicula sp. 1'),
('Appendicula','Appendicula sp. 2'),
('Appendicula','Appendicula sp. 3'),
('Appendicula','Appendicula sp. 4'),
('Appendicula','Appendicula sp. 5'),
('Blepharoglossum','Blepharoglossum condylobulbon'),
('Blepharoglossum','Blepharoglossum grossum'),
('Brachypeza','Brachypeza unguiculata'),
('Bryobium','Bryobium senile'),
('Bulbophyllum','Bulbophyllum antenniferum'),
('Bulbophyllum','Bulbophyllum colubrimodum'),
('Bulbophyllum','Bulbophyllum mucronatum subsp. alagense'),
('Bulbophyllum','Bulbophyllum odoratum'),
('Bulbophyllum','Bulbophyllum sp. 1'),
('Bulbophyllum','Bulbophyllum sp. 2'),
('Bulbophyllum','Bulbophyllum sp. 3'),
('Calanthe','Calanthe davaensis'),
('Calanthe','Calanthe cf. furcata'),
('Calanthe','Calanthe sp.'),
('Cephalantheropsis','Cephalantheropsis aff. halconensis'),
('Cheirostylis','Cheirostylis octodactyla'),
('Coelogyne','Coelogyne rochussenii'),
('Coelogyne','Coelogyne sp.'),
('Corymborkis','Corymborkis veratrifolia'),
('Cryptostylis','Cryptostylis acutata'),
('Cryptostylis','Cryptostylis taiwaniana'),
('Cylindrolobus','Cylindrolobus longissimus'),
('Cymboglossum','Cymboglossum cymbidiifolium'),
('Cystorchis','Cystorchis sp.'),
('Dendrobium','Dendrobium boosii'),
('Dendrobium','Dendrobium cf. chloranthum'),
('Dendrobium','Dendrobium orbilobulatum'),
('Dendrobium','Dendrobium planum'),
('Dendrobium','Dendrobium plicatile'),
('Dendrobium','Dendrobium pterocarpum'),
('Dendrobium','Dendrobium rhombeum'),
('Dendrobium','Dendrobium setigerum'),
('Dendrobium','Dendrobium tiongii'),
('Dendrobium','Dendrobium uniflorum'),
('Dendrochilum','Dendrochilum coccineum'),
('Dendrochilum','Dendrochilum aff. elmeri'),
('Dendrochilum','Dendrochilum glumaceum'),
('Dendrochilum','Dendrochilum migueldavidii'),
('Dendrochilum','Dendrochilum sp. 1'),
('Dendrochilum','Dendrochilum sp. 2'),
('Dienia','Dienia carinata'),
('Epiblastus','Epiblastus merrillii'),
('Epipogium','Epipogium roseum'),
('Erythrodes','Erythrodes latifolia'),
('Grammatophyllum','Grammatophyllum wallisii'),
('Lepidogyne','Lepidogyne longifolia'),
('Mycaranthes','Mycaranthes candoonensis'),
('Mycaranthes','Mycaranthes mindanaensis'),
('Oberonia','Oberonia serrulata'),
('Octarrhena','Octarrhena elmeri'),
('Odontochilus','Odontochilus marivelensis'),
('Odontochilus','Odontochilus yakushimensis'),
('Oxystophyllum','Oxystophyllum elmeri'),
('Paraphaius','Paraphaius flavus'),
('Peristylus','Peristylus goodyeroides'),
('Phaius','Phaius tankervilleae'),
('Phalaenopsis','Phalaenopsis mariae'),
('Phalaenopsis','Phalaenopsis reichenbachiana'),
('Phalaenopsis','Phalaenopsis sanderiana'),
('Pholidota','Pholidota imbricata'),
('Phreatia','Phreatia amesii'),
('Phreatia','Phreatia sulcata'),
('Phreatia','Phreatia sp. 1'),
('Phreatia','Phreatia sp. 2'),
('Pinalia','Pinalia floribunda'),
('Pinalia','Pinalia nielsenii'),
('Podochilus','Podochilus lucescens'),
('Podochilus','Podochilus plumosus'),
('Podochilus','Podochilus sp.'),
('Pteroceras','Pteroceras longicalcareum'),
('Renanthera','Renanthera monachica'),
('Rhomboda','Rhomboda lanceolata'),
('Robiquetia','Robiquetia bifidus'),
('Robiquetia','Robiquetia compressa'),
('Spathoglottis','Spathoglottis plicata'),
('Stichorkis','Stichorkis cf. compressa'),
('Stichorkis','Stichorkis gracilis'),
('Stichorkis','Stichorkis leytensis'),
('Stichorkis','Stichorkis philippinensis'),
('Taeniophyllum','Taeniophyllum philippinense'),
('Taeniophyllum','Taeniophyllum sp.'),
('Thelasis','Thelasis carinata'),
('Thrixspermum','Thrixspermum bellamabantae'),
('Thrixspermum','Thrixspermum elmeri'),
('Thrixspermum','Thrixspermum merguense'),
('Thrixspermum','Thrixspermum rostratum'),
('Thrixspermum','Thrixspermum sp.'),
('Trichotosia','Trichotosia odorifera'),
('Trichotosia','Trichotosia aff. ramosii'),
('Vanda','Vanda cootesii'),
('Vrydagzynea','Vrydagzynea sp.')
) AS s(genus, name)
JOIN genus g ON g.genus_name = s.genus
ON CONFLICT (sci_name) DO NOTHING;
